default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: greenpal_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: require
